ALTER TABLE "finishes" DROP COLUMN "labels";--> statement-breakpoint
ALTER TABLE "finishes" DROP COLUMN "created_at";--> statement-breakpoint
ALTER TABLE "finishes" DROP COLUMN "updated_at";--> statement-breakpoint
ALTER TABLE "finishes" DROP COLUMN "origin";--> statement-breakpoint
ALTER TABLE "legalities" DROP COLUMN "sort_order";--> statement-breakpoint
ALTER TABLE "legalities" DROP COLUMN "labels";--> statement-breakpoint
ALTER TABLE "legalities" DROP COLUMN "created_at";--> statement-breakpoint
ALTER TABLE "legalities" DROP COLUMN "updated_at";--> statement-breakpoint
ALTER TABLE "legalities" DROP COLUMN "origin";--> statement-breakpoint
ALTER TABLE "lessons" DROP COLUMN "sort_order";--> statement-breakpoint
ALTER TABLE "lessons" DROP COLUMN "labels";--> statement-breakpoint
ALTER TABLE "lessons" DROP COLUMN "created_at";--> statement-breakpoint
ALTER TABLE "lessons" DROP COLUMN "updated_at";--> statement-breakpoint
ALTER TABLE "lessons" DROP COLUMN "origin";--> statement-breakpoint
ALTER TABLE "rarities" DROP COLUMN "labels";--> statement-breakpoint
ALTER TABLE "rarities" DROP COLUMN "created_at";--> statement-breakpoint
ALTER TABLE "rarities" DROP COLUMN "updated_at";--> statement-breakpoint
ALTER TABLE "rarities" DROP COLUMN "origin";--> statement-breakpoint
ALTER TABLE "sub_types" DROP COLUMN "sort_order";--> statement-breakpoint
ALTER TABLE "sub_types" DROP COLUMN "labels";--> statement-breakpoint
ALTER TABLE "sub_types" DROP COLUMN "created_at";--> statement-breakpoint
ALTER TABLE "sub_types" DROP COLUMN "updated_at";--> statement-breakpoint
ALTER TABLE "sub_types" DROP COLUMN "origin";--> statement-breakpoint
ALTER TABLE "types" DROP COLUMN "sort_order";--> statement-breakpoint
ALTER TABLE "types" DROP COLUMN "labels";--> statement-breakpoint
ALTER TABLE "types" DROP COLUMN "created_at";--> statement-breakpoint
ALTER TABLE "types" DROP COLUMN "updated_at";--> statement-breakpoint
ALTER TABLE "types" DROP COLUMN "origin";